        !COMPILER-GENERATED INTERFACE MODULE: Wed Jan 26 17:26:07 2022
        MODULE COUNT__genmod
          INTERFACE 
            SUBROUTINE COUNT
            END SUBROUTINE COUNT
          END INTERFACE 
        END MODULE COUNT__genmod
